name: Java CI with Gradle

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Scarica il codice dal repository
      - uses: actions/checkout@v3

      # Installa Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Setup di Gradle (Ottimizza la cache per renderlo pi√π veloce le prossime volte)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Rende eseguibile gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Esegue il BUILD completo
      # Usa 'build' invece di 'check' per verificare anche la creazione del JAR.
      # Include automaticamente check, test, spotbugs, pmd, ecc.
      - name: Build with Gradle
        run: ./gradlew build